### ISSUE TITLE
[Request] Can override default parameters set in the avatar descriptor

### ISSUE THREAD

**Issue by kxn4t** [bdunderscore/modular-avatar#557]
Depending on the outfit I want to put on my avatar, I may want to change the parameters that are set on my avatar by default.
To achieve this, I feel that creating and setting parameter assets for each avatar would be cumbersome from an administrative standpoint.

For this reason, I want the following features.

- The MA Parameters component can override only objects with avatar descriptors.
- We can expand the parameters set in the avatar descriptor in the MA Parameters component (like the Ex menu).

Thanks!

**Comment by bdunderscore** [comment]
If I understand this correctly, you want to be able to adjust the default value of Expressions Parameters entries somehow, right?

This is a bit tricky as it breaks the general rule of nonexclusivity I try to stick with for most MA things - that is, it's not clear what to do if there are two prefabs on the same avatar that try to override the same parameter (to different values). For that matter, this issue comes up because of such a conflict - already, with a single MA Parameters component, you can set the default. It's just not clear which one "wins". I'm not sure what a good, consistent system for resolving such conflicts would be at this time...

**Comment by kxn4t** [comment]
> If I understand this correctly, you want to be able to adjust the default value of Expressions Parameters entries somehow, right?
Yes, yes that's right.

I too understand the concern that multiple components may override the same value.
Therefore, I wondered if it would be possible to avoid this concern by setting some kind of rule-based restriction, such as only allowing overrides on objects to which the avatar descriptors component has been assigned.

Currently, if the FX layers are disassembled and merged in the MA Animator component, they can be managed in the Parameters component.
However, considering the possibility that some updates may add functions, I feel that I would like to keep the avatar's own FX layers as much as possible.
(By the way, I don't really care about ExMenu because it can be re-expanded.)

**Comment by bdunderscore** [comment]
> Therefore, I wondered if it would be possible to avoid this concern by setting some kind of rule-based restriction, such as only allowing overrides on objects to which the avatar descriptors component has been assigned.

Not sure what you mean by this...?
