### ISSUE TITLE
Some renamed empty objects are removed after bakery

### ISSUE THREAD

**Issue by THEE2317** [bdunderscore/modular-avatar#598]
It happens on active avatars when in play mode and it can be replicated by baking manually. It's a case where I still need those empty objects. If it's a bug please fix it. If it‘s a feature to optimize avatar, please make the optimizing terms customizable. Thank you!<3

**Comment by THEE2317** [comment]
It happens in 2022.3.6f1 3.5.0vrcsdk 1.8.3MA

**Comment by bdunderscore** [comment]
Hi - why do you need empty object to be retained?

**Comment by THEE2317** [comment]
For example, in some cases state machine need to have a dummy animation. Many dummy animation is turning on and turning off an empty object. And in some cases an empty object is used as an anchor, not only a lighting probe and mesh root bone, but also a position anchor for some world fix animation. There are a lot of products that are using empty objects for many different propose.

**Comment by THEE2317** [comment]
In brief, it is involved in animation in certain cases.

**Comment by THEE2317** [comment]
So I have a suggestion to make the empty object culling when baking an optional toggle in menu

**Comment by bdunderscore** [comment]
To clarify - if the empty object you're animating is deleted, does this actually impact the behavior of the avatar? I'd like to make sure I have a good understanding of the circumstances under which retaining these objects is required.

**Comment by THEE2317** [comment]
It will impact

**Comment by bdunderscore** [comment]
Can you please provide a specific test case, and a description of specifically how the object removal impacts things?

The reason I'm drilling down on this is that the object removal system is a key component of both Merge Armature and the avatar menu system, so I don't want to disable it entirely - just in cases where it causes impact.

**Comment by THEE2317** [comment]
In some animation, empty objects are used to record the transform information like position, rotation and scale. In these animations, other object with mesh component or audio source or any other functioning objects will be constrained to the empty objects, like parent constraint, rotation constraint and scale constraint. By doing this, the transform of an animated object can be adjusted by empty objects and creators don't need to adjust transform of animated objects and record animation again. If the empty objects are removed the transform information stored in those empty objects will be removed too, and animated objects can't be placed in correct position and rotation.
Also even those objects are empty it still is a part of the avatar's hierarchy. The empty objects are still a part of avatar structure. Removing them will break the structure of avatar. Some empty objects are also used as testing comments for some creators, and these comments are still useful when avatar is built. There are tons of cases that empty objects are used, it's not quite possible to tell the cases where removing empty objects are totally correct.
Finally, my suggestion is still 'make the empty objects removal an optional feature', like creators can disable it on or enable it as they want.

**Comment by THEE2317** [comment]
In other words, any original objects should be retained, or be retained as many as possible, otherwise it can't be described as *non-destructive tools*.

**Comment by THEE2317** [comment]
Also it's observed at least twice that if empty objects are removed in first several builds, they are still removed incorrectly even if other functioning objects have been put in the empty objects as children. This is not non-destructive anymore. I strongly recommend not removing any original objects, even if they are empty.

**Comment by bdunderscore** [comment]
Objects referenced by constraints should be retained - if they're not, that's a bug, and I'd really appreciate some details on how to reproduce the issue. MA also doesn't remove parent objects if child objects are retained. The issue with comments is interesting... but who is looking at comments on a built and uploaded avatar?

The general goal of that optimization pass is to remove objects which don't influence the final avatar, primarily to clean up after objects which served solely to host edit-time components, or which were outfit bones, for which the mesh has already been rebased onto the base mesh's bones. Having a global on/off switch is not going to be an option, as it could lead to quite a lot of garbage remaining on the avatar, but I could consider a way to exclude specific objects from removal.

One worry I have, however, is that if I provide a way to exclude a specific object, people will use that instead of reporting the bug they're encountering, and then bugs in the optimization pass will never be fixed. That's why I'm going to push here quite hard to get those details before considering any workarounds.

So, again - please provide specific details on a setup which is broken by this optimization pass, and I'll fix it. The goal of that pass is to not do anything that would change the _behavior_ of the avatar at runtime, and so any changes to avatar behavior are a bug. But I need specifics to fix that bug; all cases I know of are handled already (again, including the constraint example!)

**Comment by THEE2317** [comment]
Details of case where MA removed parent objects after child objects (with skinned mesh component) have been put in: 
1. Empty object A is created as children under avatar. (same level with Armature) 
2. Build avatar. A is removed.
3. Put another objects B under these empty objects. 
4. Build again. A is still moved as parent of B. Build and upload and the result is the same.
How was it fixed: Changed the tag of object A to any tag then change it back to Untagged. Then A won't be remove 
This is observed in two different project. One of the MA version is 1.8.3. Another is 1.8.4.

I'm appreciate if you could make specific excluding function.

Also please exclude the empty objects that are animated in clips(it's not about constraint example but I still hope you can consider about it)
![I@3O)EO85( 7H ~OPQS5DDN](https://github.com/bdunderscore/modular-avatar/assets/123803577/6f8d5449-6ad0-4faf-98ee-40c6f088ccd1)

**Comment by bdunderscore** [comment]
In your example, behavior is correct as B is also an empty object. If object tags influence it, then that is a bug that needs fixing.

What behavior changes occur when an empty object referenced by an animation is deleted?

**Comment by THEE2317** [comment]
I have no comments anymore if you insist unnecessarily deleting objects.
