### ISSUE TITLE
MA can't control blend-shapes on main avatar directly (e.g. "shrink" blend-shapes)

### ISSUE THREAD

**Issue by Martin-H2** [bdunderscore/modular-avatar#900]
Many avatars require you to set "shrink" blend-shapes to 100% before you can apply an outfit. (e.g.: "shrink_legs" when equipping boots / thigh highs)

The "MA blend-shape Sync" can not SET blend-shapes, but only copy them from mesh to mesh. This renders MA useless for ~ 70% of booth outfits.

It would be nice to have something like a "MA blend-shape driver" that sets the blend-shape of a target mesh (e.g. main body) to a defined value and can be toggled with the MA outfit

**Comment by bdunderscore** [comment]
Have you tried the [Shape Changer component](https://modular-avatar.nadena.dev/dev/docs/reference/shape-changer) I've added to the 1.10 alphas?

**Comment by Martin-H2** [comment]
> Have you tried the [Shape Changer component](https://modular-avatar.nadena.dev/dev/docs/reference/shape-changer) I've added to the 1.10 alphas?

Well I am using the newest version I can select in VCC repo (1.9.13) and this one does not have a "Shape changer" component

**Comment by bdunderscore** [comment]
Yes, 1.10 isn't fully released yet. See https://modular-avatar.nadena.dev/docs/intro#prerelease-versions for instructions on how to enable it. Keep in mind things might not be 100% stable yet - this feature turns out to be a bit of an iceberg, there's a ton of new systems under the hood to support it that still need a bunch of tuning!

**Comment by bdunderscore** [comment]
Duplicate: https://github.com/bdunderscore/modular-avatar/issues/849#issue-2291150247 (which is in progress)
